### ISSUE TITLE
Random Syntaxes

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky3#10]
Events
```code
UserStartTypingEvent
UserActivityStartEvent
UserActivityEndEvent
UserUpdateActivityOrderEvent
GenericUserPresenceEvent
```
Effects
```code
publish|crosspost the message %message%
create annoucement channel
```
Expressions
```code
%member%.getActivities()
```
Conditions
````code
%channel% is [a] announce[ment] channel
%message% is announced|crosspos[ted]

**Comment by SkyCraft78** [comment]
✔️ UserStartTypingEvent
❌ UserActivityStartEvent
❌ UserActivityEndEvent
❌ UserUpdateActivityOrderEvent
❌ GenericUserPresenceEvent

✔️ publish|crosspost the message %message%
✔️ create announcement channel (way to turn on or off the news state of channel)

✔️ %message% is announced|crosspos[ted]
✔️ %channel% is [a] announce[ment] channel (simply check the news state)
