### ISSUE TITLE
DiSky overriding vanilla Skript "send" effect

### ISSUE THREAD

**Issue by wholenewmess** [SkyCraft78/DiSky3#23]
Skript version 2.5.3
DiSky version 3.0-beta5
Minecraft 1.17.1

The following Skript is just included to demonstrate the issue:
```
command /test:
    trigger:
        set {_e} to player
        send "test" to {_e}
```

Nothing is sent to the targeted player (in this case, {_e}). The issue is exclusive to when DiSky is active. It can be avoided by replacing 'send' with 'message' but that isn't practical.

**Comment by SkyCraft78** [comment]
Okay, so I wasn't able to fix it directly, without interfering with the Skript parser or changing the default DiSky's syntaxes.
I added a configuration file to enable or disable a specific word in DiSky's send effect pattern, which cancels the override of the Skript's send effect. (Need a reload to apply)
I'm sorry, it's maybe not what you wanted to but that's the best I can do
