### ISSUE TITLE
Disky messing with variables/yml/gui

### ISSUE THREAD

**Issue by wholenewmess** [SkyCraft78/DiSky3#25]
**I do not expect you to fix the following issue based on the limited information I've provided.** That would be a ridiculous ask. I'm just wondering if you know what might be causing this apparent conflict with YML and we can work together to figure it out.

Minecraft 1.17.1, Paper
Skript 2.5.3 & 2.6-beta3 (same results)
DiSky 3.0-ARK1

Unfortunately I don't have too much information on this issue, but it's only present when DiSky is active. 

The following is what the GUI is supposed to look like:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/25572945/136666946-a4b79350-59a2-4593-b973-06e3d32d6ab7.png">

The following is what it looks like when DiSky 3.0-ARK1 is present:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/25572945/136666960-699a8a95-a64d-4814-b910-10d8a5413a3d.png">

```
      loop indices of {{@s}::%{_spell}%::traits::*}:
            set {_items::*} to traitItems({_p}, {_spell}, loop-value, {_active})
...
            format gui slot {_slot} + {_slotCount} with {_items::1}
            format gui slot {_slot} + {_slotCount} + 9 with {_items::2}:
                if {_items::2} is not a gray stained glass pane:
                    if {_incompatible} is "no":
                        toggleTrait({_wand},{_p},{_s},{_spell},{_trait})
```

The following is also not working, image attached as well.
```
    loop {_traits::*}:
        if loop-value is not "None":
            set {_traits::%loop-index%} to "{@ca}%{{@s}::%{_activeSpell}%::traits::%loop-value%::title}%"
            
    # update wand's lore
    set {_lore::1} to "{@cm}Active Spell: {@ca}%{_activeSpell} in proper case%"
    set {_lore::2} to "{@cm}Traits: {@ca}%{_traits::*} in proper case%"
    set lore of {_p}'s tool to {_lore::*} 
```
`%{_traits::*} in proper case%` is what's not showing up properly there, when DiSky is present.

<img width="177" alt="image" src="https://user-images.githubusercontent.com/25572945/136667057-be485671-e45c-4566-976b-155ece3d4c6f.png">

I don't know much about it since one of my team developed the system, but I can at least verify the following:
- It may be an issue with skript-yaml as the GUI is pulling the data from a yml file
- It's not an issue with skript-gui as other parts of the GUI that don't require variables/yml work

Thank you!

**Comment by wholenewmess** [comment]
For what it's worth, my team member & I did a lot of testing and found that there's something to do with the way DiSky is handling variables in this version that's completely breaking them. Updating DiSky messed up our system, un-updating it fixed the issues.

Again, I don't expect a fix based on this report, but I'm providing all the info I have.

**Comment by wholenewmess** [comment]
Here's an interesting one, too. One of the core features of our system is having players sneak to regenerate their mana. With DiSky updated, this doesn't work either. It's interesting because this doesn't use tags or anything like that, it's all core Skript. Here is all the code that involves that.

```
# Add mana to player
function addMana(m: number, p: player, sneak: boolean=true):
    if {_sneak} is true:
        if {_p} is not sneaking:
            stop
    # round to prevent floating point erors
    set {{@s}::%{_p}%::mana} to floor({{@s}::%{_p}%::mana}*100) / 100
    
    # if the pool's not already full, add the mana
    if {{@s}::%{_p}%::mana} <= {{@s}::%{_p}%::max-mana}:
        add {_m} to {{@s}::%{_p}%::mana}
        
    # if the result pool is bigger than the max, set mana to max.
    if {{@s}::%{_p}%::mana} is greater than {{@s}::%{_p}%::max-mana}:
        set {{@s}::%{_p}%::mana} to {{@s}::%{_p}%::max-mana}
        
    updateMana({_p})
```

```
# Mana Regen and Update
every 0.2 seconds:
    loop all players:
        if loop-player is sneaking:
            if {{@s}::%loop-player%::mana} is less than {{@s}::%loop-player%::max-mana}:
                if block at the location 0.2 meters below loop-player is not air:
                    # Add mana and update the mana action bar 
                    addMana({{@s}::%loop-player%::mana-regen}, loop-player) 
```

Let me know if this helps or not... I think DiSky is somehow messing with variables.

**Comment by SkyCraft78** [comment]
> im also having a problem with deleting variables... when i do
> 
> ```
> if {VoteReceived::*} is set:
> 	loop indices of {VoteReceived::*}:
> 		loop {VoteReceived::%loop-value%::*}:
> 			send "Voter: %loop-value-1% // Service: %loop-value-2%" to text channel with id "{@Vote Channel}"
> 			wait 1 tick
> 	delete {VoteReceived::*}
> ```
> 
> it does not delete the variables. i have tried everything i can think of. When I remove disky, it works fine (if i modify where it sends)
> 
> here is the full code for above. the only time that i add stuff to the variable is also here.
> 
> ```
> command /testvote <text>:
> 	usage: /testvote <service>
> 	trigger:
> 		retrieve member with id "{@Minehut Bot ID}" in ("746653071794241566" parsed as guild) and store it in {_bot}
> 		set {_status} to {_bot}'s OnlineStatus
> 		
> 		# here i changed the variable for testing
> 		set {_status} to online
> 		#set {_status} to 2
> 		
> 		if "%{_status}%" is "online":
> 			send "Vter: %sender% // Service: %arg-1%" to text channel with id "{@Vote Channel}"
> 			if {VoteReceived::*} is set:
> 				loop indices of {VoteReceived::*}:
> 					loop {VoteReceived::%loop-value%::*}:
> 						send "Vter: %loop-value-1% // Service: %loop-value-2%" to text channel with id "{@Vote Channel}"
> 						wait 1 tick
> 				delete {VoteReceived::*}
> 		else:
> 			add arg-1 to {VoteReceived::%sender%::*}
> ```

Use `clear X` instead

**Comment by SkyCraft78** [comment]
> Here's an interesting one, too. One of the core features of our system is having players sneak to regenerate their mana. With DiSky updated, this doesn't work either. It's interesting because this doesn't use tags or anything like that, it's all core Skript. Here is all the code that involves that.
> 
> ```
> # Add mana to player
> function addMana(m: number, p: player, sneak: boolean=true):
>     if {_sneak} is true:
>         if {_p} is not sneaking:
>             stop
>     # round to prevent floating point erors
>     set {{@s}::%{_p}%::mana} to floor({{@s}::%{_p}%::mana}*100) / 100
>     
>     # if the pool's not already full, add the mana
>     if {{@s}::%{_p}%::mana} <= {{@s}::%{_p}%::max-mana}:
>         add {_m} to {{@s}::%{_p}%::mana}
>         
>     # if the result pool is bigger than the max, set mana to max.
>     if {{@s}::%{_p}%::mana} is greater than {{@s}::%{_p}%::max-mana}:
>         set {{@s}::%{_p}%::mana} to {{@s}::%{_p}%::max-mana}
>         
>     updateMana({_p})
> ```
> 
> ```
> # Mana Regen and Update
> every 0.2 seconds:
>     loop all players:
>         if loop-player is sneaking:
>             if {{@s}::%loop-player%::mana} is less than {{@s}::%loop-player%::max-mana}:
>                 if block at the location 0.2 meters below loop-player is not air:
>                     # Add mana and update the mana action bar 
>                     addMana({{@s}::%loop-player%::mana-regen}, loop-player) 
> ```
> 
> Let me know if this helps or not... I think DiSky is somehow messing with variables.

With that much information, I could confirm that it doesn't come from DiSky directly.
Until you use DiSky's effects, that impact and manage variables & timings, DiSky doesn't change anything else from the Skript's code.
However, feel free to send there more information in order to fix that too ^^

**Comment by wholenewmess** [comment]
Sadly no warning about a syntax change when using this version. I did get 'hasDelayBefore' errors but that seems to happen with every version.

**Comment by SkyCraft78** [comment]
> Sadly no warning about a syntax change when using this version.
Then can you send your config.yml here, please?

> I did get 'hasDelayBefore' errors but that seems to happen with every version.
DiSky doesn't support Skript 2.6, use 2.5 or the RuntimeAddonPatcher

**Comment by wholenewmess** [comment]
Closing this issue as it's covered by 
- https://github.com/SkyCraft78/DiSky3/issues/40
- https://github.com/SkyCraft78/DiSky3/issues/36
Please fix compatibility with vanilla syntaxes instead of telling people to change their vanilla syntaxes.
