### ISSUE TITLE
is online problem

### ISSUE THREAD

**Issue by ZConnorZ** [SkyCraft78/DiSky3#52]
I decided to upgrade to Skript 2.6 (not beta) and DiSky 3.6.0.
And I noticed that `is online` stopped working with the variables `{_var}`, which includes the player:
```
command /test:
    trigger:
        set {_player} to player
        if {_player} is online:
            broadcast "Yeeesss!"
        else:
            broadcast "Noooo...."
```

**Comment by SkyCraft78** [comment]
Hello ^^
Since this was already happening in v2, and I can confirm since I just verified, there's no expression or properties that use an `online` like pattern.
Even the bot's condition is `XXX is loaded`, without passing for `online`
It could then from another addon

**Comment by ZConnorZ** [comment]
Hello again. Sorry, but I checked again, removed all plugins except Skript and DiSky, and the problem still remains.
![image](https://user-images.githubusercontent.com/45974097/140600098-ee840162-2499-4837-b315-c78ab954b69c.png)
