### ISSUE TITLE
[BUG] Disky3 Make 'send ".." to loop-value' Not work!

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky3#61]
DiSky version: 3.6.0
Skript version: 2.6-nightly-3d4bd39
Plugin list:
```hs
[18:02:13 INFO]: Plugins (28): AuthMe, CMILib, DiSky, FastAsyncWorldEdit (WorldEdit), FastLogin, GSit, HolographicDisplays, HolographicDisplaysAddon*, Jobs, LuckPerms, Multiverse-Core, PerWorldInventory, ProtocolLib, RuntimeSkriptAddonPatcher, SkBee, Skellett, SkQuery, skRayFall, Skript, skript-gui*, Skript-Paper*, skript-placeholders*, skript-reflect, skript-yaml, skUtilities*, Vault, ViewDistanceTweaks, WorldGuard
```

I have test it with Disky 3 and without it so i know what i do :)
this my code
```vs
on load:
    add console to {_l::*}
    loop {_l::*}:
        send "X" to loop-value
```
This code will do a "message" to the console right?
but.. this the output after i reload it
![image](https://user-images.githubusercontent.com/64282946/144651268-bc1ffd54-659c-4b71-b4ab-720797d51011.png)

ok now i will change 'loop-value' to console directly like this
```vs
on load:
    add console to {_l::*}
    loop {_l::*}:
        send "X" to console
```
here the output
![image](https://user-images.githubusercontent.com/64282946/144651460-5f98107d-a286-4357-86ee-4ed6c3afcfb5.png)

**Comment by LowScarlet** [comment]
This also applies to players

**Comment by LowScarlet** [comment]
and I hope you unban my discord account, I'm sorry for the trouble that time, although I forgot what the problem was

**Comment by AfonsoHackers** [comment]
I am unsure if you can even do that. lol

**Comment by LowScarlet** [comment]
> I am unsure if you can even do that. lol

I have experience in scripting almost 2 years so I know what I'm doing

**Comment by SkyCraft78** [comment]
Enable the `ParsingSendEffect` from the config file, it will fix your problems and every send message effect of DiSky will be replaced by `send discord...`

**Comment by AfonsoHackers** [comment]
@LowScarlet Legit doesn't change shit cause I know skript for almost 5 years now lol. You are just using things I never used simple.
