### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky3#64]
```hs
[05:51:14 ERROR]: Can't understand this condition/effect: retrieve message with id {_id} from {_ch} with bot "enderdragon" and store it in {_msg} (discord/function.sk, line 50: retrieve message with id {_id} from {_ch} with bot "enderdragon" and store it in {_msg}')
```
{_id} output is ID from discord message
{_channel} is channel type
![image](https://user-images.githubusercontent.com/64282946/145635010-fd47344e-0464-420a-a483-e6a3d003807a.png)
![image](https://user-images.githubusercontent.com/64282946/145635034-8e7a9dfd-b0a9-414b-b004-6e4a60c0250c.png)

Skript version 2.6-nightly-3d4bd39
DiSky version 3.6.0
This server is running Paper version git-Paper-358 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3f043f7)

**Comment by AfonsoHackers** [comment]
{_msg} is a discord entity, unsure if you can parse it as a string aka broadcast it just like that.

**Comment by LowScarlet** [comment]
> {_msg} is a discord entity, unsure if you can parse it as a string aka broadcast it just like that.

I don't understand what you say

**Comment by AfonsoHackers** [comment]
@LowScarlet if you don't then please check the wiki and learn about discord entities before using this addon.

**Comment by SkyCraft78** [comment]
Hum, this is very weird, the code is been parsed for me:
![image](https://user-images.githubusercontent.com/50667548/146205204-fc830a87-c497-4a7d-af56-6ed0b950b0b9.png)
Could you try updating DiSky to 3.7 under nighty build? (check `Actions` tab on this repository)

**Comment by LowScarlet** [comment]
> Hum, this is very weird, the code is been parsed for me: ![image](https://user-images.githubusercontent.com/50667548/146205204-fc830a87-c497-4a7d-af56-6ed0b950b0b9.png) Could you try updating DiSky to 3.7 under nighty build? (check `Actions` tab on this repository)

try using in paper, not in discord parser, I try it in parser and no error but not in paper

**Comment by LowScarlet** [comment]
> Could you try updating DiSky to 3.7 under nighty build? (check Actions tab on this repository)

ok

**Comment by LowScarlet** [comment]
wait, where disky 3.7? i don't see it in `actions`
