### ISSUE TITLE
Private Channel Syntaxes

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky3#8]
Events
```code
PrivateMessageDeleteEvent
PrivateMessageUpdateEvent
PrivateMessageReceiveEvent
GenericPrivateMessageReactionEvent
```

**Comment by SkyCraft78** [comment]
These events are included in the global events of DiSky (delete an event, update event), which means whoever the message comes from guild or PM the event will fire (just check if event guild is set for example to be sure it's from PM).
For the message receive event you can use the `direct message receive` event.
